apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web-proj-268
spec:
  replicas: 1
  template:
    metadata:
      name: web-proj-268
    spec:
      containers:
      - name: web-proj-268
        image: nginx:1.16